package com.example.viewmodel

object Translator {
    private val translations = mapOf(
        "ES" to mapOf(
            "app_title" to "Bibliopolis",
            "app_subtitle" to "Lectura & Audio Offline",
            "menu_library" to "Leer Libros",
            "menu_audiobooks" to "Audiolibros",
            "menu_favorites" to "Mis Favoritos",
            "search_placeholder" to "Buscar libros por título o autor...",
            "settings_title" to "Ajustes del Sistema",
            "theme_label" to "Modo Visual",
            "theme_system" to "Por Defecto del Sistema",
            "theme_light" to "Modo Claro",
            "theme_dark" to "Modo Oscuro",
            "lang_label" to "Idioma del Reproductor",
            "date_time_label" to "Fecha y Hora Actual",
            "time_format_label" to "Formato de Hora",
            "format_12h" to "Formatos 12 Horas (AM/PM)",
            "format_24h" to "Formatos 24 Horas",
            "no_favorites" to "Aún no tienes libros favoritos marcados.",
            "empty_search" to "No se encontraron libros para tu búsqueda.",
            "chapter_label" to "Capítulo",
            "playback_speed" to "Velocidad de voz",
            "play_btn" to "Reproducir",
            "pause_btn" to "Pausar",
            "back_btn" to "Volver",
            "drawer_header_greeting" to "¡Hola, Lector!",
            "drawer_config_desc" to "Configura y personaliza tu experiencia offline."
        ),
        "EN" to mapOf(
            "app_title" to "Bibliopolis",
            "app_subtitle" to "Offline Reading & Audio",
            "menu_library" to "Read Books",
            "menu_audiobooks" to "Audiobooks",
            "menu_favorites" to "Favorites",
            "search_placeholder" to "Search books or authors...",
            "settings_title" to "System Settings",
            "theme_label" to "Theme Mode",
            "theme_system" to "System Default",
            "theme_light" to "Light Mode",
            "theme_dark" to "Dark Mode",
            "lang_label" to "Reader Language",
            "date_time_label" to "Current Date & Time",
            "time_format_label" to "Time Format",
            "format_12h" to "12-Hour Format (AM/PM)",
            "format_24h" to "24-Hour Format",
            "no_favorites" to "No favorite books bookmarked yet.",
            "empty_search" to "No books match your search.",
            "chapter_label" to "Chapter",
            "playback_speed" to "Speech speed",
            "play_btn" to "Play",
            "pause_btn" to "Pause",
            "back_btn" to "Back",
            "drawer_header_greeting" to "Hello, Reader!",
            "drawer_config_desc" to "Configure and customize your offline experience."
        ),
        "FR" to mapOf(
            "app_title" to "Bibliopolis",
            "app_subtitle" to "Lecture & Audio Hors-ligne",
            "menu_library" to "Lire des Livres",
            "menu_audiobooks" to "Livres Audio",
            "menu_favorites" to "Favoris",
            "search_placeholder" to "Rechercher des livres...",
            "settings_title" to "Paramètres Système",
            "theme_label" to "Mode d'affichage",
            "theme_system" to "Par défaut système",
            "theme_light" to "Mode Clair",
            "theme_dark" to "Mode Sombre",
            "lang_label" to "Langue du Lecteur",
            "date_time_label" to "Date et heure",
            "time_format_label" to "Format de l'heure",
            "format_12h" to "Format 12 Heures (AM/PM)",
            "format_24h" to "Format 24 Heures",
            "no_favorites" to "Aucun favori enregistré pour le moment.",
            "empty_search" to "Aucun livre ne correspond à votre recherche.",
            "chapter_label" to "Chapitre",
            "playback_speed" to "Vitesse de lecture",
            "play_btn" to "Lire",
            "pause_btn" to "Pause",
            "back_btn" to "Retour",
            "drawer_header_greeting" to "Bonjour, Lecteur !",
            "drawer_config_desc" to "Configurez et personnalisez votre expérience."
        ),
        "PT" to mapOf(
            "app_title" to "Bibliopolis",
            "app_subtitle" to "Leitura & Áudio Offline",
            "menu_library" to "Ler Livros",
            "menu_audiobooks" to "Audiolivros",
            "menu_favorites" to "Favoritos",
            "search_placeholder" to "Buscar livros por título...",
            "settings_title" to "Configurações Globais",
            "theme_label" to "Tema Visual",
            "theme_system" to "Padrão do Sistema",
            "theme_light" to "Modo Claro",
            "theme_dark" to "Modo Escuro",
            "lang_label" to "Idioma do Leitor",
            "date_time_label" to "Data e Hora atual",
            "time_format_label" to "Formato de Hora",
            "format_12h" to "Formato 12 Horas (AM/PM)",
            "format_24h" to "Formato 24 Horas",
            "no_favorites" to "Nenhum livro favoritado.",
            "empty_search" to "Nenhum livro corresponde à busca.",
            "chapter_label" to "Capítulo",
            "playback_speed" to "Velocidade de reprodução",
            "play_btn" to "Reproduzir",
            "pause_btn" to "Pausar",
            "back_btn" to "Voltar",
            "drawer_header_greeting" to "Olá, Leitor!",
            "drawer_config_desc" to "Configure e personalize sua experiência offline."
        )
    )

    fun translate(key: String, languageCode: String): String {
        return translations[languageCode]?.get(key) ?: translations["ES"]?.get(key) ?: key
    }
}
